version: '3'
services:
  oreo:
    build: .
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: secret  # change this
      MONGO_HOST: mongodb

  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret  # change this too
    volumes:
    - ./oreo-db:/data/db
